<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
        <img src="/img/item-hive.png" width="auto" height="50" alt="" loading="lazy">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/items">Items</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <?php foreach ($categories as $category) : ?>
                        <a class="dropdown-item" href="/items/?category=<?= $category["name"] ?>"><?= $category["name"]  ?></a>
                    <?php endforeach; ?>
                </div>
            </li>
        </ul>

        <form class="form-inline my-2 my-lg-0" action="/search">
            <input class="form-control mr-sm-2" type="search" name="s" placeholder="Search" aria-label="Search">
            <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
        <ul class="navbar-nav mr">
            <li class="nav-item">
                <?php if ($user_is_logged_in) : ?>
                    <a class="nav-link mx-2 px-3 bg-light text-dark rounded" href="/admin/logout">Logout</a>
                <?php else : ?>
                    <a class="nav-link mx-2 px-3 bg-light text-dark rounded" href="/login">Login</a>
                <?php endif ?>
                <?php if ($user_is_logged_in) : ?>
            <li class="nav-item">
                <a class="nav-link mx-2 px-3 text-light rounded btn-primary" href="/admin">Dashboard</a>
            </li>
        <?php endif ?>
        </li>
        </ul>

    </div>
</nav>