<div class="container text-center my-5 p-5 bg-dark text-light rounded">

    <h1>Change Password</h1>

    <form action="/admin/change_password" method="POST">
        <label class="float-left">Previous Password</label>
        <input class="form-control my-2" type="password" placeholder="Change Password..." name="new_password" id="new_password">
        <label class="float-left">Confirm Password</label>
        <input class="form-control my-2" type="password" placeholder="Confirm Password..." name="new_password_confirm" id="new_password_confirm">
        <input class="btn btn-primary" type="submit" value="Change my password!" id="submit_password">
    </form>
</div>

<script>
    $("#submit_password").on('click', function() {
        if ($("#new_password").val() != $("#new_password_confirm").val()) {
            alert("Passwords do not match");
            return false;
        }
        return true;
    });
</script>