<div class="container p-5 my-5">
    <div class="text-center bg-dark text-light rounded p-5 d-flex justify-content-center align-items-center flex-wrap">

        <div>

            <img class="" src="/img/logo-black.svg" alt="" width="120" height="150">
            <h2 class="px-3 text-light">Welcome Admin</h2>

            <div class="p-3 btn-group-vertical btn-group-lg" role="group" aria-label="First group">
                <a href="admin/pages/change_password" class="btn btn-light my-1">Change Password</a>
                <a href="admin/pages/manage_categories" class="btn btn-light my-1">Manage Categories</a>
                <a href="admin/pages/manage_products" class="btn btn-light my-1">Manage Products</a>
            </div>
        </div>

    </div>
</div>