<div class="container my-5">
    <h5 class="position-absolute px-3 py-2 text-light">Index Admin Pages</h5>
    <div class="container rounded d-flex justify-content-around align-items-center bg-dark p-5">

        <h2 class="px-3 text-light">Welcome Admin</h2>

        <div class="p-3 btn-group-vertical btn-group-lg" role="group" aria-label="First group">
            <a href="admin/pages/change_password" class="btn btn-light my-1">Change Password</a>
            <a href="admin/pages/manage_categories" class="btn btn-light my-1">Manage Categories</a>
            <a href="admin/pages/manage_products" class="btn btn-light my-1">Manage Products</a>
        </div>
    </div>
</div>