<?php
    $itemModel = model('App\Models\ItemModel');
    $items = $itemModel->getItems();
    $header = $itemModel->getHeader();
?>
<h1>Manage Products</h1>

<table>
    <thead>
        <tr>
            <?php foreach($header as $heading):?>    
                <th><?= $heading ?></th>
            <?php endforeach ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach($items as $item):?>    
            <tr>
                <?php foreach($item as $key=>$value):?>  
                    <?php if ($key == 'image'): ?>
                        <td><img width="100px" src="/<?= $value ?>" alt="<?= $value ?>"></td>
                    <?php else: ?>
                        <td><?= $value ?></td>
                    <?php endif ?>
                <?php endforeach ?>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
<table>
    <thead>
        <tr>
            <?php foreach($header as $heading):?>    
                <th><?= $heading ?></th>
            <?php endforeach ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach($items as $item):?>    
            <tr>
            <form action="">
                <?php foreach($item as $key=>$value):?>  
                    <?php if ($key == 'image'): ?>
                        <td><img width="100px" src="/<?= $value ?>" alt="<?= $value ?>"></td>
                    <?php elseif ($key == 'category'): ?>
                        <td>
                            <select name="<?=$key."-".$value?>">
                                <?php foreach($categories as $category):?>
                                    <option <?= $value == $category["name"] ? "selected" : "" ?> value="<?= $category["name"] ?>"><?= $category["name"] ?></option>
                                <?php endforeach?>
                            </select>
                        </td>
                    <?php else: ?>
                        <td><input type="text" name="<?=$key."-".$value?>" value="<?= $value ?>"></td>
                    <?php endif ?>
                <?php endforeach ?>
                <td>
                    <input type="submit" value="submit">
                    <button onclick="deleteItem(<?= $item['id'] ?>)">Delete Item</button>
                </td>
            </form>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>


<h2>Add Product</h2>
<form method="POST" action="add_product" id="add-product-form">
    <input type="text" name="item_name" placeholder="Name">
    <select name="item_category">
        <?php foreach($categories as $category):?>
            <option value="<?= $category["id"] ?>"><?= $category["name"] ?></option>
        <?php endforeach?>
    </select>
    <input type="text" name="item_price" placeholder="Price" >
    <input type="text" name="item_image" placeholder="Image" >
    <input type="text" name="item_rating" placeholder="Rating" >
    <input type="text" name="item_quantity" placeholder="Quantity" >
    <input type="text" name="item_description" placeholder="Description" >
    <input type="submit">
</form>

<div class="container my-5">

    <form class="p-5 bg-dark text-white rounded" method="POST" action="add_product">
        <h1 class="text-center">Manage Products</h1>
        <div class="form-group">
            <label>Name</label>
            <input class="form-control" type="text" name="item_name" placeholder="Name">
        </div>
        <div class="form-group">
            <label>Category</label>
            <input class="form-control" type="text" name="item_category" placeholder="Category">
        </div>
        <div class="form-group">
            <label>Price</label>
            <input class="form-control" type="text" name="item_price" placeholder="Price">
        </div>
        <div class="form-group">

            <label>Image</label>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroupFileAddon01">Upload Image</span>
                </div>
                <div class="custom-file">
                    <input type="file" class="custom-file-input" name="item_image" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                    <label class="custom-file-label" for="inputGroupFile01">Choose Image</label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label>Rating</label>
            <input class="form-control" type="text" name="item_rating" placeholder="Rating">
        </div>
        <div class="form-group">
            <label>Quantity</label>
            <input class="form-control" type="text" name="item_quantity" placeholder="Quantity">
        </div>
        <div class="form-group">
            <input class="btn btn-primary" type="submit">
        </div>
    </form>

</div>

<script>
    function deleteItem(id) {
        var r = confirm("Are you sure you want to delete the item?");
        if (r) {
            $.post("/admin/delete_item", {item_id: id}, function(data) {
                location.reload();
            })
        }
    }
</script>