<h1>Manage Categories</h1>

<table>
    <thead>
        <tr>
            <th>Category</th>
            <th>Actions</th>       
        </tr>
    </thead>
    <tbody>
        <?php foreach($categories as $category):?>
            <tr>
                <td>
                    <form action="/admin/rename_category" method="POST">
                        <input type="hidden" value="<?= $category ?>" name="previous_category">
                        <input type="text" value="<?= $category ?>" name="new_category">
                        <input type="submit" value="Change">
                    </form>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>