<div class="container bg-dark text-light my-5 p-4">

    <h1 class="text-center p-3">Manage Categories</h1>

    <table class="table table-dark">
        <thead class="thead">
            <tr>
                <th class="text-center">All Current Categories</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($categories as $category) : ?>
                <tr>
                    <td>
                        <form action="/admin/rename_category" method="POST">
                            <input type="hidden" value="<?= $category['name'] ?>" name="previous_category">
                            <div>Number of Items in this category: <?= $itemModel->getNumberOfItemsPerCategory($category['name']) ?></div>
                            <label>Category</label>
                            <input class="form-control" type="text" value="<?= $category['name'] ?>" name="new_category" maxlength="60">

                            <div class="my-2">
                                <label>Description</label>
                                <input class="form-control" type="text" value="<?= $category['description'] ?>" name="description" maxlength="100">
                            </div>
                            <input class="btn btn-primary" type="submit" value="Change">
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td>
                    Add category
                    <form action="/admin/add_category" method="POST">
                        <input class="form-control my-2" type="text" placeholder="New Category Name" name="category_name" maxlength="60">
                        <input class="form-control my-2" type="text" placeholder="New Category Description" name="category_description" maxlength="100">
                        <input class="btn btn-primary" type="submit" value="Submit">
                    </form>
                </td>
            </tr>
        </tbody>
    </table>
</div>