<div class="container my-5">

    <form class="p-5 bg-dark text-white rounded" method="POST" action="add_product">
        <h1 class="text-center">Manage Products</h1>
        <div class="form-group">
            <label>Name</label>
            <input class="form-control" type="text" name="item_name" placeholder="Name">
        </div>
        <div class="form-group">
            <label>Category</label>
            <input class="form-control" type="text" name="item_category" placeholder="Category">
        </div>
        <div class="form-group">
            <label>Price</label>
            <input class="form-control" type="text" name="item_price" placeholder="Price">
        </div>
        <div class="form-group">

            <label>Image</label>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroupFileAddon01">Upload Image</span>
                </div>
                <div class="custom-file">
                    <input type="file" class="custom-file-input" name="item_image" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                    <label class="custom-file-label" for="inputGroupFile01">Choose Image</label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label>Rating</label>
            <input class="form-control" type="text" name="item_rating" placeholder="Rating">
        </div>
        <div class="form-group">
            <label>Quantity</label>
            <input class="form-control" type="text" name="item_quantity" placeholder="Quantity">
        </div>
        <div class="form-group">
            <input class="btn btn-primary" type="submit">
        </div>
    </form>

</div>