<h1>Manage Products</h1>

<form method="POST" action="add_product">
    <input type="text" name="item_name" placeholder="Name">
    <input type="text" name="item_category" placeholder="Category" >
    <input type="text" name="item_price" placeholder="Price" >
    <input type="text" name="item_image" placeholder="Image" >
    <input type="text" name="item_rating" placeholder="Rating" >
    <input type="text" name="item_quantity" placeholder="Quantity" >
    <input type="submit">
</form>