<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="img/index-header.png" class="d-block w-100" alt="...">
            <div class="carousel-caption d-flex align-items-center">
                <div class="container-sm text-left my-5 text-dark">
                    <h2>Welcome To Item Hive!</h2>
                    <h4>Find everything you need to achieve fitness goals, connect with family, and enjoy great entertainment.</h4>
                    <a class="btn btn-primary" href="/items">Shop Now.</a>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="img/index-header-2.png" class="d-block w-100" alt="...">
            <div class="carousel-caption d-flex align-items-center">
                <div class="container-sm text-left my-5 text-dark">
                    <h2>Save on tech from the brands you love.</h2>
                    <h4>With unbeatable prices on incredible tech from Microsoft, Sony, and more.</h4>
                    <a class="btn btn-primary" href="/items">Shop Now.</a>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="img/index-header-3.png" class="d-block w-100" alt="...">
            <div class="carousel-caption d-flex align-items-center">
                <div class="container-sm text-left my-5 text-dark">
                    <h2>Find the perfect camera for you!</h2>
                    <h4>With unbeatable prices on incredible 2020 & 2019 Cameras</h4>
                    <a class="btn btn-primary" href="/items">Shop Now.</a>
                </div>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<div class="container my-4">
    <div class="card-columns">
        <?php foreach ($items as $item) : ?>
            <div class="card">
                <img class="card-img-top" src="<?= $item["image"] ?>" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title"><?= $item["name"] ?></h5>
                    <p class="card-text">Item Price: $<?= $item["price"] ?></p>
                    <p class="card-text"><?= $item["description"] ?></p>
                    <a href="/items" class="btn btn-secondary btn-sm"><small>Shop now.</small></a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>


</div>
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Enjoy the Hotest Prices with Item Hive.</h1>
        <p class="lead">Subscribe to our email for the latest notifications on releases and hot prices!</p>
    </div>
</div>