<ul>
    <?php foreach ($categories as $category) : ?>
        <li>
            <a href="?category=<?= $category ?>"><?= $category ?></a>
        </li>
    <?php endforeach; ?>
</ul>


<h1>All Items</h1>

<ul>
    <div class="card-columns">
        <?php foreach ($items as $item) : ?>


            <div class="card">
                <img class="card-img-top" src="<?= $item["image"] ?>" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title"><?= $item["name"] ?></h5>
                    <p class="card-text">Item Price: $<?= $item["price"] ?></p>
                    <p class="card-text"></p>
                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                </div>
            </div>

        <?php endforeach; ?>
    </div>
    <pre>
    <div class="panel panel-default">
        <div class="panel-heading"><?= var_dump($items) ?></div>
    </div>
    
</ul>