<ul>
    <?php foreach($categories as $category): ?>
        <li>
            <a href="?category=<?= $category["name"] ?>"><?= $category["name"] ?></a>
        </li>
    <?php endforeach;?> 
</ul>


<h1>All Items</h1>

<ul>
    <?php foreach($items as $item): ?>
        <li>
            <?= $item["name"] ?>
        </li>
    <?php endforeach;?>
    <pre>
    <div class="panel panel-default">
        <div class="panel-heading"><?= var_dump($items)?></div>
    </div>
    
</ul>
