<div class="container my-5">
    <h1 class="text-center p-4">Login Area</h1>

<form method="POST" class="rounded bg-secondary text-light p-5">
    <div class="form-group">
        <label for="exampleInputEmail1">Username</label>
        <input type="text" name="username" class="form-control" placeholder="Enter Username">

    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" name="password" placeholder="Password">
        <small id="emailHelp" class="form-text">Don't worry. Your passwords safe with us :)</small>
    </div>
    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
