<div class="container p-5 my-5">
    <div class="text-center bg-dark text-light rounded p-5 d-flex justify-content-center align-items-center flex-wrap">
        <form method="POST" class="form-signin">
            <img class="" src="/img/logo-black.svg" alt="" width="120" height="150">
            <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
            <label class="float-left">Enter Username</label>
            <input type="text" id="username" class="form-control" name="username" placeholder="Enter Username" required autofocus>
            <label class="float-left">Password</label>
            <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
            <small id="emailHelp" class="form-text float-left btn-block">Don't worry. Your passwords safe with us :)</small>

            <button class="btn btn-lg btn-primary mt-3" type="submit">Sign in</button>
            <p class="mt-4 mb-3">&copy; 2020-2021</p>
        </form>
    </div>
</div>